steps:
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'gcr.io/my-project2510/jenkins', '.']
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'gcr.io/my-project2510/rohan']
  options:
    logsBucket: 'use-case1252'
