steps:
- name: 'gcr.io/cloud-builders/gcloud'
  args: ['auth', 'activate-service-account', '--key-file=path/to/your/credentials.json']
- name: 'hashicorp/terraform:light'
  args: ['init']
- name: 'hashicorp/terraform:light'
  args: ['apply', '-auto-approve']
  env:
  - 'GOOGLE_CLOUD_PROJECT=your-project-id'
  - 'TF_VAR_region=us-central1'
  options:
    logsBucket: 'your-logs-bucket'  # Specify your Cloud Storage bucket here
