steps:
  - name: gcr.io/cloud-builders/kubectl
    args:
      - '-c'
      - >
        gcloud container clusters get-credentials gke-cluster --zone
        europe-north1-a --project winter-runway-424719-a3
 
        kubectl create deployment dep3 --image yeasy/simple-web:latest
 
        kubectl expose deployment dep3 --type LoadBalancer --port 80
    id: Set up kubeconfig
    entrypoint: sh
options:
  logging: CLOUD_LOGGING_ONLY
